"use client";

import { FileUp, Image, MessageSquare, MoreHorizontal, Paperclip, Send, Sparkles } from "lucide-react";
import { useState } from "react";

export function AIProductDemo() {
  const [prompt, setPrompt] = useState("");
  const [sent, setSent] = useState(false);
  return <div className="ai-demo"><aside className="ai-sidebar"><div className="ai-sidebar-title"><span className="mini-logo"><Sparkles size={14} /></span><strong>深度寻知</strong></div><button className="new-chat">+ 新建对话</button><div className="chat-label">最近对话</div><div className="chat-item active"><MessageSquare size={14} /> 产品定位研究</div><div className="chat-item"><MessageSquare size={14} /> API 文档摘要</div><div className="chat-item"><MessageSquare size={14} /> 中文提示词优化</div><div className="ai-sidebar-bottom"><div><span className="avatar">D</span><span>演示工作区</span></div><MoreHorizontal size={15} /></div></aside><section className="ai-chat"><div className="ai-chat-top"><div><span className="eyebrow">MODEL SELECTOR</span><strong>Example Reasoning <span>⌄</span></strong></div><div className="ai-capabilities"><span>多模型对话</span><span>文档分析</span><span>代码辅助</span></div></div><div className="message-stack"><div className="message user-message"><span className="avatar user">你</span><div><small>你 · 刚刚</small><p>帮我梳理一个 AI 工具服务平台的产品结构。</p></div></div><div className="message bot-message"><span className="mini-logo"><Sparkles size={14} /></span><div><small>深度寻知 AI · 演示回复</small><p>可以从三层结构展开：面向用户的 AI 工具体验层、面向开发者的 API 能力层，以及面向企业的部署与服务层。这样既便于理解，也方便后续扩展。</p><div className="message-pills"><span>产品结构</span><span>可继续追问</span></div></div></div>{sent && <div className="message user-message"><span className="avatar user">你</span><div><small>你 · 刚刚</small><p>{prompt}</p></div></div>}</div><div className="ai-input-wrap"><div className="ai-input"><button aria-label="上传文件"><Paperclip size={17} /></button><input value={prompt} onChange={(e) => setPrompt(e.target.value)} placeholder="输入消息，开始探索…" onKeyDown={(e) => { if (e.key === "Enter" && prompt) { setSent(true); setPrompt(""); } }} /><button aria-label="生成图像"><Image size={17} /></button><button className="send-button" aria-label="发送" onClick={() => { if (prompt) { setSent(true); setPrompt(""); } }}><Send size={15} /></button></div><small><FileUp size={12} /> 支持文档分析 · 模拟产品界面</small></div></section></div>;
}
