import Link from "next/link";
import { ArrowRight, Check, Info, ShieldAlert } from "lucide-react";
import type { Service } from "@/data/services";
import { ButtonLink } from "@/components/ui/ButtonLink";
import { Reveal } from "@/components/ui/Reveal";

export function ServiceDetail({ service }: { service: Service }) {
  const Icon = service.icon;
  return <><section className="detail-hero"><div className="container detail-hero-inner"><div><Link className="back-link" href="/services">← 返回服务目录</Link><div className={`detail-icon tone-${service.tone}`}><Icon size={28} /></div><span className="eyebrow">{service.eyebrow} / SERVICE</span><h1>{service.name}</h1><p>{service.description}</p><div className="hero-actions"><ButtonLink href="/contact">{service.cta}</ButtonLink><ButtonLink href="/help" variant="secondary">查看服务说明</ButtonLink></div></div><div className="detail-summary"><span className="eyebrow">SERVICE BRIEF</span><strong>清晰范围<br />按需评估</strong><div className="summary-rule" /><p>我们会先了解使用场景、设备环境与交付预期，再确认服务方案。</p></div></div></section><section className="section detail-body"><div className="container detail-grid"><div><span className="eyebrow">WHAT&apos;S INCLUDED / 01</span><h2>服务内容</h2><div className="bullet-grid">{service.bullets.map((bullet) => <div className="check-item" key={bullet}><span><Check size={14} /></span><strong>{bullet}</strong></div>)}</div></div><aside className="detail-aside"><div className="aside-card"><span className="eyebrow">SUITABLE FOR</span><h3>适用用户</h3>{service.audience.map((item) => <p key={item}><ArrowRight size={14} /> {item}</p>)}<Link className="text-link" href="/contact">告诉我们你的场景 <ArrowRight size={16} /></Link></div>{service.compliance && <div className="compliance-card"><ShieldAlert size={18} /><div><strong>合规提示</strong><p>{service.compliance}</p></div></div>}</aside></div></section><section className="section process-section"><div className="container"><span className="eyebrow">HOW IT WORKS / 02</span><h2>从需求到交付，<span>每一步都可确认</span></h2><div className="process-grid">{["提交需求", "确认环境", "评估方案", "技术处理", "验收交付", "售后支持"].map((step, index) => <Reveal key={step} delay={index * 0.05}><div className="process-item"><span>{String(index + 1).padStart(2, "0")}</span><Info size={15} /><strong>{step}</strong><p>{index === 0 ? "描述你的目标与约束" : index === 1 ? "了解设备与使用环境" : index === 2 ? "确认范围与交付方式" : index === 3 ? "按确认方案执行服务" : index === 4 ? "共同确认交付结果" : "提供后续问题协助"}</p></div></Reveal>)}</div></div></section></>;
}
