"use client";

import { useState } from "react";
import { CheckCircle2, Loader2, Send } from "lucide-react";

const serviceOptions = ["ChatGPT 订阅咨询", "API 服务", "国际短信验证", "网络环境部署", "AI 聚合平台", "Codex Skill 安装", "Codex 中文化", "企业定制", "售后问题", "其他"];
export function ContactForm() {
  const [loading, setLoading] = useState(false); const [success, setSuccess] = useState(false); const [error, setError] = useState("");
  const submit = async (event: React.FormEvent<HTMLFormElement>) => { event.preventDefault(); setError(""); const form = event.currentTarget; const data = new FormData(form); const email = String(data.get("email") || ""); const contact = String(data.get("contact") || ""); if (!data.get("name") || !contact || !email || !data.get("description") || !data.get("agree")) { setError("请补全必填字段，并勾选同意用户协议。"); return; } if (!/^\S+@\S+\.\S+$/.test(email)) { setError("请输入有效的电子邮箱。"); return; } if (contact.trim().length < 4) { setError("请填写有效的联系方式。"); return; } setLoading(true); await new Promise((resolve) => setTimeout(resolve, 900)); setLoading(false); setSuccess(true); form.reset(); };
  if (success) return <div className="form-success"><CheckCircle2 size={36} /><span className="eyebrow">REQUEST RECEIVED / DEMO</span><h3>信息已提交</h3><p>这是演示成功状态。真实项目上线前，需要把表单接入后端 API、邮件或工单系统。</p><button className="button button-secondary" onClick={() => setSuccess(false)}>再次提交</button></div>;
  return <form className="contact-form" onSubmit={submit}><div className="form-head"><span className="eyebrow">PROJECT BRIEF</span><h2>告诉我们你的需求</h2><p>带 * 为必填项，信息仅用于服务沟通演示。</p></div><div className="form-row"><label>姓名 *<input name="name" placeholder="你的称呼" /></label><label>联系方式 *<input name="contact" placeholder="手机 / 微信 / Telegram" /></label></div><div className="form-row"><label>电子邮箱 *<input name="email" type="email" placeholder="name@example.com" /></label><label>公司或团队名称<input name="company" placeholder="可选" /></label></div><div className="form-row"><label>服务类型<select name="service"><option value="">请选择服务</option>{serviceOptions.map((item) => <option key={item}>{item}</option>)}</select></label><label>预算范围<select name="budget"><option>暂不确定</option><option>按量计费</option><option>需要咨询报价</option><option>企业项目评估</option></select></label></div><label>需求描述 *<textarea name="description" rows={5} placeholder="请描述你想解决的问题、已有环境和期望结果…" /></label><div className="form-row"><label>期望交付时间<input name="timeline" placeholder="例如：两周内 / 暂无明确时间" /></label><label>是否需要企业定制<select name="custom"><option>暂不确定</option><option>是</option><option>否</option></select></label></div><label className="checkbox-label"><input name="agree" type="checkbox" /> <span>我已阅读并同意<a href="/terms">用户协议</a>，了解当前表单为演示提交。</span></label>{error && <p className="form-error">{error}</p>}<button className="button button-primary submit-button" disabled={loading}>{loading ? <><Loader2 size={16} className="spin" /> 提交中…</> : <>提交需求 <Send size={16} /></>}</button><small className="form-footnote">后端 API 接口预留 · 暂未接入真实支付或订单系统</small></form>;
}
